// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCummcot5LJkUkVG_WYMlI1H2w98IswDcw',
    appId: '1:928621659189:web:5b5e9124856dc6abdc5d7c',
    messagingSenderId: '928621659189',
    projectId: 'random-1128d',
    authDomain: 'random-1128d.firebaseapp.com',
    storageBucket: 'random-1128d.appspot.com',
    measurementId: 'G-66B4QJ8EXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnhiH1iZ4QmyaEwvdzcj9Stlhxkc7vm_4',
    appId: '1:928621659189:android:e50449c2acec5c2adc5d7c',
    messagingSenderId: '928621659189',
    projectId: 'random-1128d',
    storageBucket: 'random-1128d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj6-pzFr_9j50lXJ2j3jN7vrUvcszKUA',
    appId: '1:928621659189:ios:2b04405ddb8327d2dc5d7c',
    messagingSenderId: '928621659189',
    projectId: 'random-1128d',
    storageBucket: 'random-1128d.appspot.com',
    iosClientId: '928621659189-l155i69b727i0u1i69hqi1ubgjereprd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj6-pzFr_9j50lXJ2j3jN7vrUvcszKUA',
    appId: '1:928621659189:ios:05f3394ef9e7d9f2dc5d7c',
    messagingSenderId: '928621659189',
    projectId: 'random-1128d',
    storageBucket: 'random-1128d.appspot.com',
    iosClientId: '928621659189-c5f6pjh72vguq1kjh8iqo5joqjdr2bu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify.RunnerTests',
  );
}
